version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

  tg_proxy:
    build: ./client
    restart: on-failure
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    depends_on:
      - app
